schedules:
  - name: Workdays
    start: "07:00:00"
    end: "18:00:00"
    days_of_week: Mon-Thu,Fri

ical_calendars:
  - source: "https://vg-sh.church.tools/?q=public/cr_ical&security=PR8Pv2arR0Y4ppAp7S4OQKugsomDFHqq&id=70"
    name: Saal
  - source: "https://vg-sh.church.tools/?q=public/cr_ical&security=XvncfKdYSOQdM5mrTPDoRUVOALnecEwY&id=72"
    name: Kleiner Saal
  - source: "https://vg-sh.church.tools/?q=public/cr_ical&security=hbHbDFvPL6118WqBej8KuAQ29ZqwfV9G&id=71"
    name: Küche
  - source: "https://vg-sh.church.tools/?q=public/cr_ical&security=dQ6LthOtSIhkWeQ8oWSuACcvgVDqedGu&id=73"
    name: Kinderstunde
  - source: "https://vg-sh.church.tools/?q=public/cr_ical&security=Q5dSZEqfJg3O6J15noYiWDl7BGWLxXpq&id=74"
    name: Teenkreis

heating:
  cold: 17.0
  warm: 21.0

assignments:
  - tadozone: Büro
    earlystart: "00:30:00"
    calendar_names:
      - Workdays
      - Saal
      - Kleiner Saal
      - Küche
